import { calcMetrics } from '../store';
import { getBenchmark } from '../data/benchmarks';

export function generateReportHTML(data) {
  const m = calcMetrics(data);
  const b = getBenchmark(data?.icp?.industry);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>PMF Report - ${new Date().toLocaleDateString()}</title>
  <style>
    body { font-family: system-ui; max-width: 800px; margin: 0 auto; padding: 40px; color: #333; }
    h1 { color: #1e40af; }
    .metric { background: #f8fafc; padding: 16px; border-radius: 8px; margin: 12px 0; }
    .pmf-strong { background: #dcfce7; color: #166534; }
    .pmf-medium { background: #fef3c7; color: #92400e; }
    .pmf-weak { background: #fee2e2; color: #991b1b; }
    .footer { margin-top: 40px; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <h1>PMF Report</h1>
  <p>Generated ${new Date().toISOString().slice(0, 10)}</p>
  
  <h2>Summary</h2>
  <div class="metric pmf-${m.pmfScore}">
    <strong>PMF Score: ${m.pmfScore.toUpperCase()}</strong>
  </div>
  
  <h2>Metrics</h2>
  <div class="metric">Total Leads: ${m.totalLeads}</div>
  <div class="metric">Response Rate: ${m.responseRate}% (benchmark avg: ${b.responseRate.avg}%)</div>
  <div class="metric">Interviews: ${m.interviewCount}</div>
  <div class="metric">Problem Rate: ${m.problemRate}% (benchmark avg: ${b.problemRate.avg}%)</div>
  <div class="metric">Willingness to Pay: ${m.willingnessRate}% (benchmark avg: ${b.willingnessRate.avg}%)</div>
  ${m.seRate != null ? `<div class="metric">Sean Ellis (Very disappointed): ${m.seRate}% (40% = PMF)</div>` : ''}
  
  <div class="footer">Generated by PMF Finder</div>
</body>
</html>`;
}
